clone:
    path: github.com/vmware/docker-volume-vsphere
    tags: true

build:
  build_dev:
    image: cnastorage/vibauthor-and-go:0.6
    commands:
      - go get github.com/golang/lint/golint
      - make build
    when:
      event: [push, pull_request]


  build_tag:
    image: cnastorage/vibauthor-and-go:0.6
    commands:
      - export PKG_VERSION=$$TAG
      - echo $PKG_VERSION
      - go get github.com/golang/lint/golint
      - make build
    when:
      event: tag

  package:
    image: cnastorage/fpm
    commands:
      - make deb rpm
    when:
      event: [push, pull_request]

  package_tag:
    image: cnastorage/fpm
    commands:
      - export PKG_VERSION=$$TAG
      - echo $PKG_VERSION
      - make deb rpm
    when:
      event: tag

  test:
    image: cnastorage/vibauthor-and-go:0.6
    privileged: true
    environment:
      - GOVC_USERNAME=$$CI_VMWARE_ESX_USER
      - GOVC_PASSWORD=$$CI_VMWARE_ESX_PASS
      - GOVC_INSECURE=1
      - GOVC_URL=$$CI_ESX_IP
    commands:
      - export VM1=`govc vm.ip photon.rc.vmfs`
      - export VM2=`govc vm.ip Ubuntu.1404.vmfs`
      - echo $GOVC_URL
      - echo $VM1
      - echo $VM2
      - ./misc/drone-scripts/deploy-and-test-wrapper.sh $GOVC_URL $VM1 $VM2 $$BUILD_NUMBER < /dev/null
    when:
      event: [push, pull_request]

  test_tag:
    image: cnastorage/vibauthor-and-go:0.6
    privileged: true
    environment:
      - GOVC_USERNAME=$$CI_VMWARE_ESX_USER
      - GOVC_PASSWORD=$$CI_VMWARE_ESX_PASS
      - GOVC_INSECURE=1
      - GOVC_URL=$$CI_ESX_IP
    commands:
      - export PKG_VERSION=$$TAG
      - export VM1=`govc vm.ip ubuntu`
      - export VM2=`govc vm.ip photon.rc`
      - ./misc/drone-scripts/deploy-and-test-wrapper.sh $GOVC_URL $VM1 $VM2 $$BUILD_NUMBER < /dev/null
    when:
      event: tag

matrix:
  GO_VERSION:
    - 1.6

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: vmware/docker-volume-vsphere
    tag:
      - "latest"
      - $$BRANCH-$$BUILD_NUMBER
    file: misc/dockerfiles/Dockerfile.vmdk-plugin
    privileged: true
    storage_driver: overlay
    when:
      branch: master

  github_release:
    api_key: $$GITHUB_TOKEN
    files:
      - build/*.deb
      - build/*.rpm
      - build/*.vib
      - build/*.zip
    when:
      event: tag
